<?php
/** @var \Dotsquares\Shopby\Block\Navigation\Widget\Tooltip $block */
/** @var \Magento\Framework\Escaper $escaper */

$content = $block->getContent();
?>
<?php if ($content): ?>
    <script type="text/x-magento-init">
        {
            ".ds-filter-items-<?= $escaper->escapeHtml($block->getFilterSetting()->getAttributeCode()) ?>": {
                "dsShopbyFilterAddTooltip": {
                    "content": <?= /* @noEscape */ $block->jsonEncode($content) ?>,
                    "tooltipTemplate": <?= /* @noEscape */ $block->jsonEncode($block->getTooltipTemplate()) ?>
                }
            }
        }
    </script>
<?php endif; ?>
