<?php
/**
 * @var $block \Dotsquares\Shopby\Block\Adminhtml\System\Config\Field\Renderer\SliderColor
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<section class="dsshopby-slider-settings -color"
         data-bind="
            scope: 'dsshopby_slider_settings',
                mageInit: {
                    'Magento_Ui/js/core/app': {
                        components: {
                            'dsshopby_slider_settings': {
                                component: 'Dotsquares_Shopby/js/components/slider-settings',
                                default: {
                                    style: '<?= $escaper->escapeHtml($block->getSliderStyle()) ?>',
                                    color: '<?= $escaper->escapeHtml($block->getSliderColor()) ?>',
                                    options: <?= $escaper->escapeHtml($block->getSliderStyleOptions()) ?>
                                }
                        }
                    }
                }
            }">
    <input name="groups[slider][fields][slider_color][value]"
           class="input-text admin__control-text"
           type="text"
           data-bind="
               afterRender: function (node) {
                    initColorPicker(node);
               },
               style: {
                    backgroundColor: color
               },
               attr: {
                   value: color
               }">
</section>
