<?php
/** @var $block \Dotsquares\ShopbyPage\Block\Adminhtml\Page\Selection */
?>
<script>
    require([
        'Dotsquares_ShopbyPage/js/selection'
    ], function (selection) {
        selection.init(
            '<?= $block->escapeUrl($block->getSelectionUrl()) ?>',
            '<?= $block->escapeUrl($block->getAddSelectionUrl())?>',
            '<?= $block->escapeHtml($block->getCounter())?>'
        );
        window.dotsquaresShopbyPageSelection = selection;
    });
</script>
