<?php
/**
 * @var \Dotsquares\ShopbyBase\Model\FilterSetting $filterSetting
 * @var \Dotsquares\Shopby\Block\Navigation\FilterRenderer $block
 * @var \Magento\Framework\Escaper $escaper
 */

$postfix = uniqid();
$filterCode = $filterSetting->getAttributeCode();
$max = ceil($fromToConfig['max']);
$min = floor($fromToConfig['min']);
$sliderStyle = $block->getSliderStyle();
$sliderColor = $block->getSliderColor();
?>

<div class="dsshopby-slider-wrapper <?= $escaper->escapeHtmlAttr($sliderStyle) ?>">
    <div class="items ds-filter-items-<?= $escaper->escapeHtmlAttr($filterCode) ?>">
        <form data-dsshopby-filter="<?= $escaper->escapeHtmlAttr($filterCode) ?>"
              data-dsshopby-filter-request-var="<?= $escaper->escapeHtmlAttr($block->getFilter()->getRequestVar()) ?>">
            <div id="ds-shopby-filter-<?= $escaper->escapeHtmlAttr($filterCode . '_' . $postfix) ?>"
                 class="dsshopby-slider-container dsshopby_currency_rate <?= $escaper->escapeHtmlAttr($sliderStyle) ?>"
                 data-ds-js="slider-container"
                 data-min="<?= $escaper->escapeHtmlAttr($min) ?>"
                 data-max="<?= $escaper->escapeHtmlAttr($max) ?>"
                 data-rate="<?= /* @noEscape */ $fromToConfig['curRate'] ?>">
                <input data-dsshopby-slider-id="value"
                       type=hidden
                       name="dsshopby[<?= $escaper->escapeHtmlAttr($block->getFilter()->getRequestVar())?>][]"/>
                <div data-dsshopby-slider-id="slider" class="ds-slider"></div>
                <div data-dsshopby-slider-id="display"
                     class="dsshopby-slider-display"
                     data-ds-js="slider-display"></div>
            </div>
        </form>
    </div>

    <?php if ($filterSetting->getAddFromToWidget()): ?>
        <?= /* @noEscape */ $block->getFromToWidget('slider') ?>
    <?php endif; ?>
</div>

<script type="text/x-magento-init">
    {
        "#ds-shopby-filter-<?= $escaper->escapeHtml($filterCode . '_' . $postfix); ?>": {
            "dsShopbyFilterSlider": {
                "style": "<?= $escaper->escapeHtml($sliderStyle) ?>",
                "colors": { "main": "<?= $escaper->escapeHtml($sliderColor) ?>"},
                "collectFilters": <?= /* @noEscape */ $block->collectFilters() ?>,
                "template":"<?= $escaper->escapeHtml($fromToConfig['template']) ?>",
                "currencySymbol":"<?= $escaper->escapeHtml($fromToConfig['currencySymbol']) ?>",
                "currencyPosition":"<?= $escaper->escapeHtml($fromToConfig['currencyPosition']) ?>",
                "step":<?= /* @noEscape */ $escaper->escapeHtml(floatval($fromToConfig['step'])) ?>,
                "from": "<?= /* @noEscape */ $fromToConfig['from'] ?>",
                "to": "<?= /* @noEscape */ $fromToConfig['to'] ?>",
                "deltaFrom": "<?= /* @noEscape */ $fromToConfig['deltaFrom'] ?>",
                "deltaTo": "<?= /* @noEscape */ $fromToConfig['deltaTo'] ?>",
                "curRate": "<?= /* @noEscape */ $fromToConfig['curRate'] ?>",
                "min":<?= (float)$min ?>,
                "max":<?= (float)$max ?>,
                "url": "<?= /* @noEscape */ $block->getSliderUrlTemplate() ?>",
                "code":"<?= $escaper->escapeHtml($filterSetting->getAttributeModel()->getAttributeCode()) ?>",
                "hideDisplay": <?= /* @noEscape */ $filterSetting->getAddFromToWidget() ? "1" : '0' ?>
            }
        }
    }
</script>
