<?php
/** @var \Dotsquares\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Dotsquares\Shopby\Block\Navigation\FilterRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */

use Dotsquares\Shopby\Model\Source\SubcategoriesExpand;

$filterUniqId = $escaper->escapeHtml(uniqid());
$filterCode = $escaper->escapeHtml($filterSetting->getAttributeCode());
?>

<?php if ($filterSetting->isShowSearchBox($filterItems->getCount())): ?>
    <?= /* @noEscape */ $block->getSearchForm() ?>
<?php endif; ?>

<form data-dsshopby-filter="<?= /* @noEscape */ $filterCode ?>"
      data-dsshopby-filter-request-var="<?= /* @noEscape */ $block->getFilter()->getRequestVar() ?>">
    <ul class="items ds-filter-items-<?= /* @noEscape */ $filterCode ?> ds-labels-folding
    <?= /* @noEscape */ $block->isMultiselect($filterSetting) ? '-ds-multiselect' : '-ds-singleselect' ?>"
        <?php if ($block->getEnableOverflowScroll($filterSetting) > 0): ?>
            style="max-height:<?= /* @noEscape */ $block->getOverflowScrollValue($filterSetting) ?>px;
                    overflow-y: auto;
                    overflow-x: hidden;"
        <?php endif; ?>>
        <?= /* @noEscape */ $categoryTreeHtml ?>
    </ul>
</form>

<?php if ($filterSetting->getSubcategoriesExpand() == SubcategoriesExpand::BY_CLICK): ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "dsShopbyFilterCollapse": {
                "mode": "folding",
                "collapseSelector": "<?= /* @noEscape */ $block->isTopNav() ? '.dotsquares-catalog-topnav' : '.sidebar' ?>"
            }
        }
    }
    </script>
<?php endif; ?>
