<?php
/** @var \Dotsquares\Shopby\Block\Navigation\ApplyButton $block */
/** @var \Magento\Framework\Escaper $escaper */

use Dotsquares\Shopby\Block\Navigation\UrlModifier;

$postfix = uniqid();
?>

<?php if ($block->blockEnabled()): ?>
    <?php if (!$block->isAjaxEnabled()): ?>
        <form data-dsshopby-filter="">
            <input type="hidden"
                   name="<?= /* @noEscape */ UrlModifier::VAR_REPLACE_URL ?>"
                   value="1"/>
        </form>
    <?php endif; ?>
    <div class="ds_shopby_apply_filters">
        <div class="ds-show-button -horizontal">
            <span class="ds-items"></span>
            <button dsshopby-apply-filter="1"
                    id="dotsquares_shopby_apply_filters_<?= /* @noEscape */ $postfix ?>"
                    data-mage-init='{"dsShopbyApplyFilters":{
                        "ajaxEnabled": <?= /* @noEscape */ ($block->isAjaxEnabled() ? '1' : '0') ?>,
                        "navigationSelector": "<?= $escaper->escapeHtml($block->getNavigationSelector()) ?>",
                        "clearUrl": "<?= $escaper->escapeUrl($block->getClearUrl()) ?>",
                        "buttonPosition": "<?= $escaper->escapeHtml($block->getButtonPosition()) ?>"
                    }}'
                    title="<?= $escaper->escapeHtmlAttr(__('Apply Filters')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Apply Filters')) ?>"
                    class="dsshopby-button">
                <?= $escaper->escapeHtml(__('Apply')) ?>
            </button>
        </div>
    </div>
<?php endif; ?>
